import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import dotenv from 'dotenv';
dotenv.config();

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

const packages = [
  {
    name: 'Goa Beach Paradise',
    destination: 'Goa',
    state: 'Goa',
    shortDescription: 'Sun, sand and seafood on the golden beaches of Goa with vibrant nightlife.',
    description: 'Experience the stunning beaches, vibrant nightlife, and Portuguese heritage of Goa. From the buzzing shores of Baga and Calangute to the peaceful Palolem in the south, this 5-day package covers the best of what Goa has to offer. Enjoy water sports, explore historic churches, and savour fresh seafood.',
    pricePerPerson: 17500,
    durationDays: 5,
    durationNights: 4,
    category: 'Beach',
    availableSeats: 20,
    hotelCategory: '3 Star',
    accommodation: 'Beach-facing hotel with pool',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'November to February',
    itinerary: 'Day 1: Arrive Goa, check-in, evening at Baga Beach\nDay 2: North Goa – Calangute, Anjuna, Vagator beaches, flea market\nDay 3: Old Goa heritage – Basilica of Bom Jesus, Se Cathedral, Fontainhas\nDay 4: South Goa – Palolem Beach, Colva, water sports\nDay 5: Dudhsagar Falls excursion, departure',
    inclusions: 'Hotel accommodation (4 nights)\nDaily breakfast\nAirport/station transfers\nLocal sightseeing by AC vehicle\nProfessional guide',
    exclusions: 'Airfare/train tickets to Goa\nLunch and dinner\nPersonal expenses\nEntry tickets to monuments\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 7 days before travel. 50% refund for 3–7 days. No refund within 3 days.',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
  },
  {
    name: 'Kerala Backwaters Houseboat',
    destination: 'Alleppey',
    state: 'Kerala',
    shortDescription: 'Cruise the serene backwaters of Kerala on a traditional houseboat.',
    description: 'Drift through the lush backwaters of Alleppey aboard a traditional kettuvallam houseboat. Witness village life along the waterways, enjoy fresh Kerala cuisine, and relax amid coconut groves and paddy fields. Combined with the hill station of Munnar and the cultural city of Kochi.',
    pricePerPerson: 22500,
    durationDays: 6,
    durationNights: 5,
    category: 'Nature',
    availableSeats: 15,
    hotelCategory: 'Houseboat',
    accommodation: 'Traditional houseboat + hill resort',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'September to March',
    itinerary: 'Day 1: Arrive Kochi, Fort Kochi sightseeing, Kathakali performance\nDay 2: Drive to Munnar, tea garden visit\nDay 3: Munnar – Eravikulam National Park, Mattupetty Dam\nDay 4: Drive to Alleppey, board houseboat, backwater cruise\nDay 5: Continue cruise to Kollam, village walks\nDay 6: Kovalam Beach, departure from Trivandrum',
    inclusions: 'Houseboat stay (1 night) + resort (4 nights)\nBreakfast and dinner daily\nAll transfers\nLocal sightseeing\nKathakali show tickets',
    exclusions: 'Travel to Kerala\nLunch\nPersonal expenses\nAdventure activity charges\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 10 days before travel. 40% refund for 5–10 days. No refund within 5 days.',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
  },
  {
    name: 'Rajasthan Royal Heritage Tour',
    destination: 'Jaipur–Jodhpur–Jaisalmer',
    state: 'Rajasthan',
    shortDescription: 'Majestic forts, golden deserts and royal palaces across the land of kings.',
    description: 'Travel through the majestic forts, colourful bazaars, and golden sand dunes of Rajasthan. From the Pink City of Jaipur to the Blue City of Jodhpur and the Golden City of Jaisalmer, this 7-day tour covers the royal heritage of India\'s most iconic state. End with a magical camel safari under the stars.',
    pricePerPerson: 27800,
    durationDays: 7,
    durationNights: 6,
    category: 'Heritage',
    availableSeats: 18,
    hotelCategory: '4 Star',
    accommodation: 'Heritage hotels and havelis',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to March',
    itinerary: 'Day 1: Arrive Jaipur, Amber Fort, City Palace\nDay 2: Jaipur – Hawa Mahal, Jantar Mantar, local bazaars\nDay 3: Drive to Pushkar, Brahma Temple, Pushkar Lake\nDay 4: Drive to Jodhpur, Mehrangarh Fort, Jaswant Thada\nDay 5: Drive to Jaisalmer, Sonar Fort\nDay 6: Sam Sand Dunes, camel safari, cultural evening\nDay 7: Departure from Jaisalmer',
    inclusions: 'Heritage hotel accommodation (6 nights)\nDaily breakfast\nAll transfers by AC vehicle\nLocal sightseeing\nCamel safari at Sam Dunes\nProfessional guide',
    exclusions: 'Travel to Rajasthan\nLunch and dinner\nPersonal expenses\nEntry tickets\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 7 days before travel. 50% refund for 3–7 days. No refund within 3 days.',
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800',
  },
  {
    name: 'Manali Snow & Adventure',
    destination: 'Manali',
    state: 'Himachal Pradesh',
    shortDescription: 'Snow peaks, river rafting, paragliding and the scenic Rohtang Pass.',
    description: 'Manali is a paradise for adventure seekers and nature lovers alike. This 6-day package takes you through snow-capped Himalayan peaks, the thrilling Rohtang Pass, river rafting on the Beas, and peaceful Himalayan villages. Perfect for groups and couples seeking an active mountain holiday.',
    pricePerPerson: 18750,
    durationDays: 6,
    durationNights: 5,
    category: 'Adventure',
    availableSeats: 12,
    hotelCategory: '3 Star',
    accommodation: 'Mountain resort with valley views',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to June',
    itinerary: 'Day 1: Arrive Manali, hotel check-in, Mall Road evening\nDay 2: Solang Valley – skiing, zorbing, paragliding\nDay 3: Rohtang Pass excursion (weather permitting)\nDay 4: Kullu – river rafting on Beas, Manikaran hot springs\nDay 5: Old Manali, Hadimba Devi Temple, Vashisht village\nDay 6: Departure from Manali',
    inclusions: 'Hotel accommodation (5 nights)\nDaily breakfast\nAll transfers\nSolang Valley activity pass\nRiver rafting session\nProfessional guide',
    exclusions: 'Travel to Manali\nLunch and dinner\nPersonal expenses\nAdditional adventure activities\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 5 days before travel. 50% refund for 2–5 days. No refund within 2 days.',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
  },
  {
    name: 'Andaman Island Getaway',
    destination: 'Port Blair–Havelock–Neil Island',
    state: 'Andaman & Nicobar Islands',
    shortDescription: 'Crystal-clear waters, white beaches and vibrant coral reefs in the Andamans.',
    description: 'Discover one of India\'s best-kept secrets — the Andaman Islands. Pristine white beaches, crystal-clear turquoise waters, and some of the finest coral reefs in the world await you. This 7-day package covers the historic Cellular Jail in Port Blair, the world-famous Radhanagar Beach in Havelock, and the peaceful Neil Island.',
    pricePerPerson: 34500,
    durationDays: 7,
    durationNights: 6,
    category: 'Island',
    availableSeats: 10,
    hotelCategory: '4 Star',
    accommodation: 'Beach resort + island hotel',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to May',
    itinerary: 'Day 1: Arrive Port Blair, Cellular Jail, light and sound show\nDay 2: Ross Island, North Bay Island snorkelling\nDay 3: Ferry to Havelock Island, Radhanagar Beach\nDay 4: Havelock – Elephant Beach scuba diving\nDay 5: Ferry to Neil Island, Bharatpur and Laxmanpur beaches\nDay 6: Return Port Blair, Anthropological Museum\nDay 7: Corbyn\'s Cove Beach, departure',
    inclusions: 'Hotel accommodation (6 nights)\nDaily breakfast\nAll inter-island ferry tickets\nLocal sightseeing\nSnorkelling session\nProfessional guide',
    exclusions: 'Flights to Port Blair\nLunch and dinner\nScuba diving charges\nPersonal expenses\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 14 days before travel. 30% refund for 7–14 days. No refund within 7 days.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
  },
  {
    name: 'Varanasi Spiritual Journey',
    destination: 'Varanasi',
    state: 'Uttar Pradesh',
    shortDescription: 'Witness the Ganga Aarti and ancient ghats of India\'s holiest city.',
    description: 'Varanasi is one of the world\'s oldest living cities and the spiritual capital of India. Experience the mesmerising Ganga Aarti at Dashashwamedh Ghat, take a sunrise boat ride on the sacred Ganges, and explore ancient temples and narrow lanes. A soulful journey that stays with you forever.',
    pricePerPerson: 12200,
    durationDays: 4,
    durationNights: 3,
    category: 'Spiritual',
    availableSeats: 25,
    hotelCategory: '3 Star',
    accommodation: 'Heritage guesthouse near the ghats',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to March',
    itinerary: 'Day 1: Arrive Varanasi, evening Dashashwamedh Ghat Aarti\nDay 2: Sunrise boat ride on Ganges, Kashi Vishwanath Temple, Sarnath\nDay 3: Ghats walk – Manikarnika, Assi, Tulsi Ghat, silk weaving workshop\nDay 4: Morning meditation, Ramnagar Fort, departure',
    inclusions: 'Hotel accommodation (3 nights)\nDaily breakfast\nAirport/station transfers\nLocal sightseeing\nBoat ride on Ganges',
    exclusions: 'Travel to Varanasi\nLunch and dinner\nPersonal expenses\nTemple entry fees\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 5 days before travel. 50% refund for 2–5 days. No refund within 2 days.',
    imageUrl: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800',
  },
  {
    name: 'Kashmir Paradise on Earth',
    destination: 'Srinagar–Gulmarg–Pahalgam',
    state: 'Jammu & Kashmir',
    shortDescription: 'Dal Lake shikaras, snow-covered Gulmarg and the meadows of Pahalgam.',
    description: 'Kashmir truly lives up to its reputation as Paradise on Earth. Float on a shikara across the mirror-like Dal Lake, ski down the slopes of Gulmarg, and walk through the flower-filled meadows of Pahalgam. This 7-day package captures Kashmir at its most magical.',
    pricePerPerson: 31500,
    durationDays: 7,
    durationNights: 6,
    category: 'Hill Station',
    availableSeats: 14,
    hotelCategory: '4 Star',
    accommodation: 'Houseboat on Dal Lake + hill hotel',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'April to October',
    itinerary: 'Day 1: Arrive Srinagar, houseboat check-in, shikara ride on Dal Lake\nDay 2: Mughal Gardens – Nishat, Shalimar, Chashme Shahi\nDay 3: Day trip to Gulmarg, gondola ride\nDay 4: Drive to Pahalgam, Betaab Valley, Aru Valley\nDay 5: Pahalgam horse riding and meadow walks\nDay 6: Return Srinagar, local market shopping\nDay 7: Departure',
    inclusions: 'Houseboat (2 nights) + hotel (4 nights)\nBreakfast and dinner\nAll transfers by AC vehicle\nGondola ride (Phase 1)\nShikara ride\nProfessional guide',
    exclusions: 'Flights to Srinagar\nLunch\nPersonal expenses\nAdventure activities\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 10 days before travel. 40% refund for 5–10 days. No refund within 5 days.',
    imageUrl: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?w=800',
  },
  {
    name: 'Ladakh Himalayan Odyssey',
    destination: 'Leh–Nubra–Pangong',
    state: 'Ladakh',
    shortDescription: 'High-altitude deserts, turquoise lakes and ancient Buddhist monasteries.',
    description: 'Ladakh is unlike any other destination in India — a surreal high-altitude landscape of barren mountains, turquoise lakes, and ancient Buddhist monasteries. This 8-day itinerary takes you from the bustling Leh market to the stark beauty of Nubra Valley and the breathtaking Pangong Tso lake.',
    pricePerPerson: 38500,
    durationDays: 8,
    durationNights: 7,
    category: 'Adventure',
    availableSeats: 10,
    hotelCategory: 'Boutique Hotel',
    accommodation: 'Boutique hotels and camps',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'June to September',
    itinerary: 'Day 1: Arrive Leh, acclimatisation rest\nDay 2: Leh – Shanti Stupa, Leh Palace, local market\nDay 3: Monasteries – Hemis, Thiksey, Rancho School\nDay 4: Drive to Nubra Valley via Khardung La pass\nDay 5: Nubra – Diskit Monastery, Hunder sand dunes, Bactrian camels\nDay 6: Drive to Pangong Tso lake\nDay 7: Pangong sunrise, return to Leh\nDay 8: Departure',
    inclusions: 'Hotel and camp accommodation (7 nights)\nBreakfast and dinner\nAll transfers by SUV\nInner Line Permits\nMonastery sightseeing\nProfessional guide',
    exclusions: 'Flights to Leh\nLunch\nPersonal expenses\nAdventure activities\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 14 days before travel. 30% refund for 7–14 days. No refund within 7 days.',
    imageUrl: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800',
  },
  {
    name: 'Golden Triangle – Delhi Agra Jaipur',
    destination: 'Delhi–Agra–Jaipur',
    state: 'Delhi / UP / Rajasthan',
    shortDescription: 'India\'s most iconic circuit covering the Taj Mahal, Red Fort and Amber Fort.',
    description: 'The Golden Triangle is India\'s most popular tourist circuit for good reason. In just 6 days you get to experience the Mughal grandeur of Delhi and Agra and the royal Rajput heritage of Jaipur. The centrepiece is the iconic Taj Mahal — a UNESCO World Heritage Site and one of the Seven Wonders of the World.',
    pricePerPerson: 21000,
    durationDays: 6,
    durationNights: 5,
    category: 'Heritage',
    availableSeats: 20,
    hotelCategory: '4 Star',
    accommodation: 'City hotels in Delhi, Agra, Jaipur',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to March',
    itinerary: 'Day 1: Arrive Delhi, Red Fort, Chandni Chowk, India Gate\nDay 2: Qutub Minar, Humayun\'s Tomb, Lotus Temple, drive to Agra\nDay 3: Taj Mahal sunrise, Agra Fort, Fatehpur Sikri\nDay 4: Drive to Jaipur, Chand Baori stepwell\nDay 5: Jaipur – Amber Fort, City Palace, Hawa Mahal, Jantar Mantar\nDay 6: Local bazaars, departure from Jaipur',
    inclusions: 'Hotel accommodation (5 nights)\nDaily breakfast\nAll transfers by AC vehicle\nLocal sightseeing\nTaj Mahal entry ticket\nProfessional guide',
    exclusions: 'Flights/train to Delhi\nLunch and dinner\nPersonal expenses\nOther entry tickets\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 7 days before travel. 50% refund for 3–7 days. No refund within 3 days.',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
  },
  {
    name: 'Coorg Coffee Plantation Retreat',
    destination: 'Coorg',
    state: 'Karnataka',
    shortDescription: 'Misty hills, coffee estates, waterfalls and the Scotland of India.',
    description: 'Known as the Scotland of India, Coorg is a lush hill station nestled in the Western Ghats. Famous for its sprawling coffee and spice plantations, cascading waterfalls, and Kodava culture, this 4-day retreat is perfect for those seeking peace, nature, and fresh mountain air away from city life.',
    pricePerPerson: 14200,
    durationDays: 4,
    durationNights: 3,
    category: 'Hill Station',
    availableSeats: 16,
    hotelCategory: 'Premium Resort',
    accommodation: 'Coffee estate resort',
    mealsIncluded: 'Breakfast and dinner',
    transportIncluded: false,
    sightseeingIncluded: true,
    bestTimeToVisit: 'October to March',
    itinerary: 'Day 1: Arrive Coorg, coffee plantation walk, resort check-in\nDay 2: Abbey Falls, Raja\'s Seat, Madikeri Fort, local market\nDay 3: Dubare Elephant Camp, Iruppu Falls, spice garden tour\nDay 4: Namdroling Monastery (Golden Temple), departure',
    inclusions: 'Resort accommodation (3 nights)\nBreakfast and dinner\nAll transfers\nCoffee plantation tour\nDubare Elephant Camp visit\nProfessional guide',
    exclusions: 'Travel to Coorg\nLunch\nPersonal expenses\nAdventure activities\nTravel insurance',
    cancellationPolicy: 'Free cancellation up to 5 days before travel. 50% refund for 2–5 days. No refund within 2 days.',
    imageUrl: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=800',
  },
];

const departures = [
  // Goa (10+ cities - mix of train, flight, bus)
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Goa', transportMode: 'TRAIN' as const, transportPrice: 1200 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Goa', transportMode: 'FLIGHT' as const, transportPrice: 2800 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Goa', transportMode: 'FLIGHT' as const, transportPrice: 3500 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Goa', transportMode: 'TRAIN' as const, transportPrice: 1800 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Goa', transportMode: 'FLIGHT' as const, transportPrice: 4500 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Goa', transportMode: 'BUS' as const, transportPrice: 900 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Goa', transportMode: 'TRAIN' as const, transportPrice: 1500 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Goa', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Jaipur', departureState: 'Rajasthan', destination: 'Goa', transportMode: 'FLIGHT' as const, transportPrice: 4200 },
  { departureCity: 'Kochi', departureState: 'Kerala', destination: 'Goa', transportMode: 'TRAIN' as const, transportPrice: 1600 },

  // Kerala / Alleppey (10+ cities)
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 4000 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Alleppey', transportMode: 'TRAIN' as const, transportPrice: 1800 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Alleppey', transportMode: 'TRAIN' as const, transportPrice: 1500 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 5000 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 3500 },
  { departureCity: 'Coimbatore', departureState: 'Tamil Nadu', destination: 'Alleppey', transportMode: 'BUS' as const, transportPrice: 800 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 5200 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 4200 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Alleppey', transportMode: 'FLIGHT' as const, transportPrice: 4500 },
  { departureCity: 'Madurai', departureState: 'Tamil Nadu', destination: 'Alleppey', transportMode: 'TRAIN' as const, transportPrice: 1200 },

  // Rajasthan (10+ cities)
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1000 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'FLIGHT' as const, transportPrice: 3800 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'FLIGHT' as const, transportPrice: 5200 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1900 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1200 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1600 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'FLIGHT' as const, transportPrice: 5000 },
  { departureCity: 'Indore', departureState: 'Madhya Pradesh', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1100 },
  { departureCity: 'Lucknow', departureState: 'Uttar Pradesh', destination: 'Jaipur–Jodhpur–Jaisalmer', transportMode: 'TRAIN' as const, transportPrice: 1300 },

  // Manali (10+ cities - mix of bus, train, flight)
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 800 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Manali', transportMode: 'TRAIN' as const, transportPrice: 1200 },
  { departureCity: 'Chandigarh', departureState: 'Punjab', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 600 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Manali', transportMode: 'FLIGHT' as const, transportPrice: 4200 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Manali', transportMode: 'TRAIN' as const, transportPrice: 1800 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Manali', transportMode: 'FLIGHT' as const, transportPrice: 5000 },
  { departureCity: 'Amritsar', departureState: 'Punjab', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 700 },
  { departureCity: 'Jaipur', departureState: 'Rajasthan', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 1100 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Manali', transportMode: 'FLIGHT' as const, transportPrice: 5500 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Manali', transportMode: 'TRAIN' as const, transportPrice: 2000 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Manali', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Ludhiana', departureState: 'Punjab', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 650 },
  { departureCity: 'Shimla', departureState: 'Himachal Pradesh', destination: 'Manali', transportMode: 'BUS' as const, transportPrice: 400 },

  // Andaman (10+ cities)
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 5500 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 6500 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 5800 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 6200 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 5900 },
  { departureCity: 'Bhubaneswar', departureState: 'Odisha', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 5200 },
  { departureCity: 'Visakhapatnam', departureState: 'Andhra Pradesh', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 5500 },
  { departureCity: 'Kochi', departureState: 'Kerala', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 6000 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Port Blair–Havelock–Neil Island', transportMode: 'FLIGHT' as const, transportPrice: 6300 },

  // Varanasi (10+ cities)
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 900 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Varanasi', transportMode: 'FLIGHT' as const, transportPrice: 4000 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 1100 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Varanasi', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Varanasi', transportMode: 'FLIGHT' as const, transportPrice: 4500 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 1700 },
  { departureCity: 'Patna', departureState: 'Bihar', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 400 },
  { departureCity: 'Lucknow', departureState: 'Uttar Pradesh', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 600 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Varanasi', transportMode: 'FLIGHT' as const, transportPrice: 4200 },
  { departureCity: 'Jaipur', departureState: 'Rajasthan', destination: 'Varanasi', transportMode: 'TRAIN' as const, transportPrice: 1400 },

  // Kashmir (10+ cities - mix of flight, train, bus)
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'FLIGHT' as const, transportPrice: 3500 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'TRAIN' as const, transportPrice: 1800 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'FLIGHT' as const, transportPrice: 5000 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'TRAIN' as const, transportPrice: 2400 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'FLIGHT' as const, transportPrice: 5500 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'FLIGHT' as const, transportPrice: 5800 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'FLIGHT' as const, transportPrice: 5200 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'TRAIN' as const, transportPrice: 2200 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'TRAIN' as const, transportPrice: 2000 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'TRAIN' as const, transportPrice: 2300 },
  { departureCity: 'Amritsar', departureState: 'Punjab', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'BUS' as const, transportPrice: 1200 },
  { departureCity: 'Chandigarh', departureState: 'Punjab', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'BUS' as const, transportPrice: 1000 },
  { departureCity: 'Jammu', departureState: 'Jammu & Kashmir', destination: 'Srinagar–Gulmarg–Pahalgam', transportMode: 'BUS' as const, transportPrice: 600 },

  // Ladakh (10+ cities - mostly flight, some bus for nearby)
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 4500 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Leh–Nubra–Pangong', transportMode: 'BUS' as const, transportPrice: 1800 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6000 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6500 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6800 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6200 },
  { departureCity: 'Srinagar', departureState: 'Jammu & Kashmir', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 2500 },
  { departureCity: 'Srinagar', departureState: 'Jammu & Kashmir', destination: 'Leh–Nubra–Pangong', transportMode: 'BUS' as const, transportPrice: 1500 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 7000 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6400 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 6100 },
  { departureCity: 'Chandigarh', departureState: 'Punjab', destination: 'Leh–Nubra–Pangong', transportMode: 'FLIGHT' as const, transportPrice: 4800 },
  { departureCity: 'Manali', departureState: 'Himachal Pradesh', destination: 'Leh–Nubra–Pangong', transportMode: 'BUS' as const, transportPrice: 1200 },

  // Golden Triangle (10+ cities)
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Delhi–Agra–Jaipur', transportMode: 'FLIGHT' as const, transportPrice: 3500 },
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Delhi–Agra–Jaipur', transportMode: 'FLIGHT' as const, transportPrice: 4000 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Delhi–Agra–Jaipur', transportMode: 'FLIGHT' as const, transportPrice: 4200 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 1600 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 1400 },
  { departureCity: 'Ahmedabad', departureState: 'Gujarat', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 1500 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 1700 },
  { departureCity: 'Lucknow', departureState: 'Uttar Pradesh', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 800 },
  { departureCity: 'Chandigarh', departureState: 'Punjab', destination: 'Delhi–Agra–Jaipur', transportMode: 'TRAIN' as const, transportPrice: 900 },
  { departureCity: 'Kochi', departureState: 'Kerala', destination: 'Delhi–Agra–Jaipur', transportMode: 'FLIGHT' as const, transportPrice: 4500 },

  // Coorg (10+ cities)
  { departureCity: 'Bangalore', departureState: 'Karnataka', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 600 },
  { departureCity: 'Chennai', departureState: 'Tamil Nadu', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 1200 },
  { departureCity: 'Mumbai', departureState: 'Maharashtra', destination: 'Coorg', transportMode: 'FLIGHT' as const, transportPrice: 3800 },
  { departureCity: 'Hyderabad', departureState: 'Telangana', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 1500 },
  { departureCity: 'Kochi', departureState: 'Kerala', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 900 },
  { departureCity: 'Mysore', departureState: 'Karnataka', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 350 },
  { departureCity: 'Delhi', departureState: 'Delhi', destination: 'Coorg', transportMode: 'FLIGHT' as const, transportPrice: 5000 },
  { departureCity: 'Pune', departureState: 'Maharashtra', destination: 'Coorg', transportMode: 'FLIGHT' as const, transportPrice: 3900 },
  { departureCity: 'Mangalore', departureState: 'Karnataka', destination: 'Coorg', transportMode: 'BUS' as const, transportPrice: 500 },
  { departureCity: 'Kolkata', departureState: 'West Bengal', destination: 'Coorg', transportMode: 'FLIGHT' as const, transportPrice: 5200 },
];

async function main() {
  console.log('Seeding database...');

  await prisma.package.deleteMany();
  await prisma.departureLocation.deleteMany();
  await prisma.user.deleteMany();
  console.log('Cleared existing data');

  // Create admin user
  const bcrypt = await import('bcryptjs');
  const adminPassword = await bcrypt.hash('Neymar@10', 12);
  await prisma.user.create({
    data: { name: 'Admin', email: 'mjv3140@gmail.com', password: adminPassword, role: 'ADMIN', emailVerified: true },
  });
  console.log('✓ Admin user: mjv3140@gmail.com / Neymar@10');

  for (const pkg of packages) {
    const created = await prisma.package.create({ data: pkg });
    console.log(`✓ Package: ${created.name}`);
  }

  for (const dep of departures) {
    await prisma.departureLocation.create({ data: dep });
  }
  console.log(`✓ Created ${departures.length} departure routes`);

  console.log(`\nSeed complete! ${packages.length} packages + ${departures.length} departure routes.`);
}

main()
  .catch((e) => { console.error('Seed failed:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); await pool.end(); });
